import json

blocks = [
  { "type": "image_group", "images": ["/images/m1_lecon3_1.png", "/images/m1_lecon3_2.png"] },
  { "type": "instruction", "content": "Consigne : Observez ce que vous voyez et prédisez le thème de la leçon." },
  { "type": "question", "content": "1. Que voyez-vous dans ces images ?" },
  { "type": "input", "content": "" },
  { "type": "input", "content": "" },
  { "type": "question", "content": "2. Selon vous, quel est le thème de la leçon ?" },
  { "type": "input", "content": "" },
  { "type": "input", "content": "" },
  { "type": "task", "content": "Micro-tâche 1 : Exprimez-vous avec votre propre style ?" },
  { "type": "instruction", "content": "Consigne : Écrivez deux phrases pour expliquer ce qu’est le covoiturage." },
  { "type": "input", "content": "" },
  { "type": "input", "content": "" },
  { "type": "phase", "content": "Phase 2 : Action (Compréhension approfondie)" },
  { "type": "instruction", "content": "Consigne : Lisez le texte, puis répondez aux questions." },
  { "type": "paragraph", "content": "Le covoiturage : voyager ensemble pour une vie plus simple" },
  { "type": "paragraph", "content": "Le covoiturage, c’est le fait de partager sa voiture avec d’autres personnes qui vont dans la même direction. Ce n’est pas un service de transport professionnel : le conducteur ne fait pas de bénéfice, il partage seulement les frais du trajet, comme l’essence ou les péages. Ce mode de déplacement connaît un grand succès en France. Les routes sont souvent pleines, le carburant coûte cher et les transports publics ne couvrent pas toujours toutes les zones. Dans ce contexte, le covoiturage apparaît comme une solution économique, écologique et solidaire. Il permet de rouler moins cher, de rencontrer du monde et de réduire la pollution." },
  { "type": "paragraph", "content": "Beaucoup de gens racontenturs expériences positives. Par exemple, Antoine, un étudiant de Nantes, dit qu’il a découvert cette pratique grâce à une application mobile : « J’ai tout de suite aimé l’ambiance dans la voiture. On discute, on écoute de la musique, et le trajet paraît plus court. » Pour lui, le covoiturage est une manière agréable de faire des rencontres tout en économisant de l’argent. D’autres apprécient surtout le côté écologique : en remplissant une seule voiture au lieu de trois, on émet beaucoup moins de CO₂. Selon le ministère de la Transition écologique, chaque année, plusieurs millions de trajets sont réalisés ainsi, ce qui prouve que cette habitude entre vraiment dans le quotidien des Français." },
  { "type": "paragraph", "content": "Mais il ne faut pas oublier les petits inconvénients. Parfois, les horaires ne sont pas respectés ou les trajets changent au dernier moment. Il arrive aussi qu’on ne s’entende pas avec les autres passagers. Certaines personnes préfèrent conduire seules, par confort ou par besoin d’intimité. Pourtant, malgré ces petits problèmes, le covoiturage reste une solution moderne et responsable. Il montre qu’on peut changer nos habitudes de transport sans perdre notre liberté. Voyager ensemble, c’est aussi apprendre à partager, à faire confiance et à penser un peu plus à la planète." },
  { "type": "link", "url": "https://www.bien-ecrire.com" },
  { "type": "header", "content": "Questions guidées (10 minutes)" },
  { "type": "instruction", "content": "Choisissez la bonne réponse :" },
  { "type": "mcq", "id": "m1l3_q1", "question": "1. Le covoiturage permet de…", "options": [{"id": "a", "text": "Voyager plus cher"}, {"id": "b", "text": "Économiser de l'argent"}, {"id": "c", "text": "Acheter une voiture"}], "correctAnswer": "b" },
  { "type": "mcq", "id": "m1l3_q2", "question": "2. Selon le texte, le covoiturage est…", "options": [{"id": "a", "text": "Un service professionnel de transport"}, {"id": "b", "text": "Une solution écologique et solidaire"}, {"id": "c", "text": "Une obligation légale"}], "correctAnswer": "b" },
  { "type": "mcq", "id": "m1l3_q3", "question": "3. Les passagers apprécient surtout…", "options": [{"id": "a", "text": "Les horaires stricts"}, {"id": "b", "text": "Les rencontres et la discussion"}, {"id": "c", "text": "Conduire seuls"}], "correctAnswer": "b" },
  { "type": "task", "content": "Micro-tâches 2 : (5 minutes)" },
  { "type": "question", "content": "Trouvez dans le texte trois avantages et un inconvénient du covoiturage ?" },
  { "type": "input", "content": "" },
  { "type": "input", "content": "" },
  { "type": "info_box", "title": "Présentation du texte explicatif", "content": "Le texte explicatif est un texte qui a pour objectif d’expliquer un phénomène, un événement ou un concept pour le faire comprendre au lecteur.\n\nCaractéristiques principales:\n• Il donne des informations précises.\n• Il utilise des connecteurs logiques : car, parce que, ainsi, donc, cependant…\n• Il présente causes, conséquences, solutions.\n• Il peut contenir des exemples pour aider à comprendre.\n\nDans le texte sur le covoiturage, l’auteur :\n• Définit le covoiturage.\n• Explique ses avantages économiques et écologiques.\n• Évoque certains inconvénients.\n• Illustre ses propos par des exemples et des témoignages." },
  { "type": "task", "content": "Micro tâche 3 : (5 minutes)" },
  { "type": "question", "content": "Identifiez l’idée essentielle du texte ?" },
  { "type": "input", "content": "" },
  { "type": "task", "content": "Micro-tâches 4 : (5 minutes)" },
  { "type": "question", "content": "Résumez chaque paragraphe en une phrase ?" },
  { "type": "input", "content": "" },
  { "type": "input", "content": "" },
  { "type": "task", "content": "Micro-tâches 5 : (5 minutes)" },
  { "type": "question", "content": "Déterminez les phrases difficiles à comprendre pour vous." },
  { "type": "input", "content": "" },
  { "type": "header", "content": "Mettez vrai ou faux devant chaque phrase : (5 minutes)" },
  { "type": "mcq", "id": "m1l3_q4", "question": "1. Le covoiturage est un service professionnel.", "options": [{"id": "a", "text": "Vrai"}, {"id": "b", "text": "Faux"}], "correctAnswer": "b" },
  { "type": "mcq", "id": "m1l3_q5", "question": "2. Il permet de réduire les embouteillages.", "options": [{"id": "a", "text": "Vrai"}, {"id": "b", "text": "Faux"}], "correctAnswer": "a" },
  { "type": "mcq", "id": "m1l3_q6", "question": "3. Le covoiturage ne contribue pas à l’écologie.", "options": [{"id": "a", "text": "Vrai"}, {"id": "b", "text": "Faux"}], "correctAnswer": "b" },
  { "type": "mcq", "id": "m1l3_q7", "question": "4. Il favorise les relations sociales.", "options": [{"id": "a", "text": "Vrai"}, {"id": "b", "text": "Faux"}], "correctAnswer": "a" },
  { "type": "task", "content": "Micro-tâches 6 : (5 minutes) : Corrigez les phrases suivantes ?" },
  { "type": "question", "content": "1. Le covoiturage réduire la pollution." },
  { "type": "input", "content": "" },
  { "type": "question", "content": "2. Les passagers partage les frais." },
  { "type": "input", "content": "" },
  { "type": "question", "content": "3. C’est une solution économique et il protège l’environnement." },
  { "type": "input", "content": "" },
  { "type": "question", "content": "4. Beaucoup personnes utilisent covoiturage." },
  { "type": "input", "content": "" },
  { "type": "task", "content": "Micro-tâches 7 : (5 minutes) Reformulez la phrase suivante ?" },
  { "type": "instruction", "content": "Consigne : Reformulez cette phrase en utilisant vos propres mots. « Il permet de rouler moins cher, de rencontrer du monde et de réduire la pollution. »" },
  { "type": "input", "content": "" },
  { "type": "task", "content": "Micro-tâches 8 : Mini-production : (5 minutes)" },
  { "type": "instruction", "content": "Rédigez deux phrases pour mettre en valeur les avantages du covoiturage." },
  { "type": "input", "content": "" },
  { "type": "input", "content": "" },
  { "type": "header", "content": "Structures à observer : (5 minutes)" },
  { "type": "grammar_card", "title": "1. Exprimer l'utilité / l'avantage", "description": "", "structure": "Il permet de + infinitif", "examples": ["• Il permet de rouler moins cher, de rencontrer du monde et de réduire la pollution."] },
  { "type": "grammar_card", "title": "2. Exprimer la conséquence", "description": "", "structure": "ce qui + verbe", "examples": ["• ce qui prouve que cette habitude entre vraiment dans le quotidien des Français."] },
  { "type": "task", "content": "Micro tâche 9 : (5 minutes)" },
  { "type": "instruction", "content": "Regardez cette vidéo pour bien comprendre ce que signifie le covoiturage :\nhttps://toutenfrancais.tv/fle-covoiturage-a2" },
  { "type": "paragraph", "content": "Rédigez un court résumé de ce que vous avez compris de cette vidéo." },
  { "type": "input", "content": "" },
  { "type": "input", "content": "" },
  { "type": "task", "content": "Micro-tâches 10 : Discussion en groupes : (10 minutes)" },
  { "type": "paragraph", "content": "En observant cette carte mentale discutez avec vos collèges sur les éléments essentiels du covoiturage." },
  { "type": "input", "content": "" },
  { "type": "phase", "content": "Phase 3 : Post-action (Tâche finale) Durée : (20 minutes)" },
  { "type": "paragraph", "content": "Tâche finale (avec modèle + aide lexicale)" },
  { "type": "instruction", "content": "Consigne: Chaque étudiant utilise les idées générées pendant la discussion.\nImaginez que vous êtes membre d’un club universitaire de développement durable. Écrivez un texte (8-10 lignes) pour inciter les étudiants à utiliser le covoiturage." },
  { "type": "paragraph", "content": "📌 Le texte doit contenir:" },
  { "type": "list_item", "content": "• Une définition du covoiturage." },
  { "type": "list_item", "content": "• Son importance pour les étudiants et les habitants." },
  { "type": "list_item", "content": "• Les avantages principaux (économiques, écologiques, sociaux)." },
  { "type": "list_item", "content": "• Les difficultés possibles liées au covoiturage." },
  { "type": "list_item", "content": "• Une conclusion motivante incitant à changer les habitudes de transport." },
  { "type": "paragraph", "content": "📌 Outils interactifs fournis:" },
  { "type": "list_item", "content": "• Banque de connecteurs : d’abord, ensuite, en plus, par exemple, mais, pourtant, enfin…" },
  { "type": "list_item", "content": "• Aide lexicale : covoiturage, trajet, partager, frais, carburant, pollution, application, convivial, écologie…" },
  { "type": "input", "content": "" },
  { "type": "input", "content": "" },
  { "type": "input", "content": "" },
  { "type": "input", "content": "" },
  { "type": "phase", "content": "Phase 4 : Évaluation des produits des étudiants : Durée : 10 minutes" },
  { "type": "paragraph", "content": "Lisez votre produit écrit et identifiez vos erreurs (vocabulaire, grammaire, orthographe), comparez avec vos camarades et corrigez le texte si nécessaire." },
  { "type": "header", "content": "É- évaluation : (10 minutes)" },
  { "type": "question", "content": "− Écrivez trois idées secondaires du texte ?" },
  { "type": "input", "content": "" },
  { "type": "question", "content": "− Pourquoi certains étudiants ne font-ils pas de covoiturage ?" },
  { "type": "input", "content": "" },
  { "type": "question", "content": "− Identifiez les mots clés du texte ?" },
  { "type": "input", "content": "" },
  { "type": "question", "content": "− Trouvez un (autre) titre qui reflète bien le texte ?" },
  { "type": "input", "content": "" },
  { "type": "question", "content": "− Quelles solutions le texte propose-t-il pour encourager le covoiturage ?" },
  { "type": "input", "content": "" },
  { "type": "question", "content": "− En petit groupe, déterminez avec tes camarades des autres causes qui empêchent le covoiturage ?" },
  { "type": "input", "content": "" },
  { "type": "question", "content": "− Pensez-vous que ce texte encourage le covoiturage ? Justifiez votre réponse à partir du texte ?" },
  { "type": "input", "content": "" }
]

with open("src/module1_refined.json", "r", encoding="utf-8") as f:
    data = json.load(f)

data["lessons"][2]["blocks"] = blocks

with open("src/module1_refined.json", "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Lesson 3 correctly formatted!")
