export const ESSAY_ANSWERS: Record<string, Record<string, string>> = {
  "Leçon 1 : Le réchauffement climatique": {
    "Pourquoi l’auteur fait-il attention à ses achats ?": "Pour réduire la pollution et privilégier des produits locaux et de saison.",
    "Quels moyens de transport privilégie-t-il ?": "Les transports en commun, la marche à pied et le vélo.",
    "Quel rôle le consommateur peut-il jouer ?": "Le consommateur peut influencer le marché en choisissant des produits écologiques, réduisant ainsi la production polluante.",
    "Déterminez les mots-clés dans le texte et leurs significations selon le contexte) 5 minutes)": "Consommateur : personne qui achète des produits.\nProduits polluants : produits qui causent la pollution.\nCircuits courts : achat de produits locaux.\nTransports en commun : bus, métro, train.\nSacs plastiques : sacs qui polluent l'environnement.",
    "Micro tâche 2 : Trouvez l’idée générale du texte ? (5 minutes)": "Chacun peut agir pour réduire le réchauffement climatique et contribuer à la protection de l’environnement.",
    "Micro-tâches 3 : (5 minutes) : Identifiez les connecteurs": "Alors : pour montrer une conséquence.\nAussi : pour ajouter une information.\nMais : pour introduire une opposition.",
    "Micro-tâches 4 : (10 minutes) Résumez chaque paragraphe en une phrase ?": "1. Chacun peut agir.\n2. L'auteur privilégie des gestes quotidiens locaux et évite les plastiques.\n3. Malgré les limites, les comportements changent.",
    "Micro-tâches 5 : (5 minutes) Déterminez les phrases difficiles à comprendre pour vous ?": "Le texte nous montre comment chacun peut agir au quotidien.",
    "Micro-tâches 6 : (5 minutes) Reformulez la phrase suivante ?": "Il évite les sacs plastiques car ils polluent les océans.",
    "Micro-tâches 7 : Mini-production (5 minutes)": "Dans ma vie, je fais des comportements écologiques, j'utilise les transports en commun et je trie mes déchets.",
    "Micro-tâches 9 : Discussion en groupes (10 minutes)": "Réduire le plastique, encourager le recyclage, la marche, le vélo.",
    "La demande : En tant qu’étudiant, rédigez article (8 à 10 lignes) pour sensibiliser vos camarades aux comportement simples qui réduisent le réchauffement climatique. La publication doit être claire, motivante et adaptée aux réseaux sociaux.": "Le réchauffement climatique est important. À l'université, on peut réduire l'impact : éviter plastique, utiliser transports en commun, acheter local. Agissons pour un monde meilleur !",
    "− Écrivez quatre idées secondaires ?": "Réduire plastique, recyclage, favoriser transports.",
    "− Pourquoi l’auteur pense-t-il que les actions individuelles sont importantes ?": "Elles réduisent la pollution et sensibilisent la société.",
    "− Donnez un autre exemple d’action écologique que l’auteur aurait pu mentionner ?": "Utilisation d'énergies renouvelables.",
    "− Identifiez les mots clés du texte ?": "Réchauffement climatique, environnement, pollution, acteurs écologiques.",
    "− Trouvez un (autre) titre qui donne bien la clé du texte ?": "Des pratiques simples pour sauver l'environnement.",
    "− Qui doit agir contre le réchauffement climatique ?": "Individus, gouvernements, entreprises.",
    "− Identifiez l’opinion de l’auteur et ses arguments principaux.": "La protection est collective, les actions simples réduisent les effets.",
    "− Comparez ces pratiques économiques de l’auteur pour la protection de l’environnement selon votre propre expérience.": "J'essaie d'économiser l'énergie et réduire les déchets.",
    "− Proposez une critique ou un commentaire sur les actions proposées.": "Elles doivent être accompagnées de mesures gouvernementales.",
    "− En petit groupe, déterminez avec tes camarades des autres causes de réchauffement climatique.": "Transport polluant, surconsommation, pollution industrielle."
  },
  "Leçon 2 : Les espaces verts": {
    "Micro-tâche 1 : Écrivez deux phrases pour expliquer ce qu’est un espace vert selon vous ?": "Ce sont des lieux naturels en ville. Ils offrent lieux de détente.",
    "Micro-tâches 3 : (5 minutes) Trouvez dans le texte trois activités qu’on peut faire dans un espace vert ?": "Jouer, lire un livre, pique-niquer, se promener.",
    "Micro tâche 4: (5 minutes) Trouvez l’idée générale du texte?": "Les avantages des espaces verts et les activités.",
    "Micro-tâches 5 : (10 minutes) Résumez chaque paragraphe en une phrase ?": "Les espaces verts sont importants. Ils ont des activités pour tous. Ils sont en danger.",
    "Micro-tâches 7 : (5 minutes) Reformulez la phrase suivante ?": "Les espaces verts aident à réduire la pollution.",
    "Micro-tâches 8 : Mini-production : (5 minutes)": "Ils sont menacés par la pollution et les constructions. Protégeons-les.",
    "Micro-tâches 10 : Discussion en groupes : (10 minutes) :": "Réduire plastique, recyclage, transports.",
    "Déterminez quatre idées secondaires du texte ?": "Améliorent air, habitat animaux, température, danger de disparition.",
    "Quels animaux peuvent y vivre ?": "Les oiseaux et insectes.",
    "Pourquoi certains espaces verts disparaissent-ils ?": "A cause des constructions et pollution.",
    "Identifiez les mots clés du texte ?": "Espaces verts, animaux, pollution, protection.",
    "Trouvez un (autre) titre qui donne bien la clé du texte ?": "L'importance de protection des espaces verts.",
    "Quelles solutions le texte propose-t-il ?": "Planter arbres, réduire pollution.",
    "Comparez ces pratiques économiques de l’auteur pour la protection de l’environnement avec votre propre expérience.": "Je plante des fleurs.",
    "En petit groupe, déterminez avec tes camarades d’autres causes de la disparition des espaces verts": "Manque de politiques environnementales.",
    "Quels sont les avantages des espaces verts en ville ?": "Améliorent qualité air.",
    "Que font les adultes dans les espaces verts ?": "Pique-niques, lecture.",
    "Pourquoi les espaces verts sont-ils importants pour les animaux ?": "Nourriture et habitat.",
    "Quelles sont les causes de la disparition des espaces verts ?": "Constructions.",
    "Comment peut-on protéger les espaces verts ?": "Planter arbres."
  },
  "Leçon 3 : Le covoiturage": {
    "Que voyez-vous dans ces images ?": "Voitures, passagers.",
    "Selon vous, quel est le thème de la leçon ?": "Le covoiturage.",
    "Micro-tâche 1 : Exprimez-vous avec votre propre style ?": "Partager une voiture pour même direction.",
    "Micro-tâches 2 : (5 minutes) Trouvez dans le texte trois avantages et un inconvénient du covoiturage ?": "Economie, écologie, rencontres. Inconvénient: horaires.",
    "Micro tâche 3 : (5 minutes) Identifiez l’idée essentielle du texte ?": "Covoiturage = transport économique et écologique.",
    "Micro-tâches 4 : (5 minutes) Résumez chaque paragraphe en une phrase ?": "Partage frais. Aspect social. Solution responsable.",
    "Micro-tâches 6 : (5 minutes) : Corrigez les phrases suivantes ?": "Le covoiturage réduit la pollution. Les passagers partagent les frais.",
    "Micro-tâches 7 : (5 minutes) Reformulez la phrase suivante ?": "Il aide à diminuer la pollution.",
    "Micro-tâches 8 : Mini-production : (5 minutes)": "Réduire frais, trafic, pollution, favorise échanges.",
    "Micro-tâches 10 : Discussion en groupes : (10 minutes)": "Créer groupe réseaux, panneaux d'affichage."
  },
    "Leçon 1 : La vie dans le passé": {
    "Consigne : Observez ce que vous voyez et prédisez le sujet ou le thème du texte.": "Ce texte parle de la vie dans le passé et des différences avec la vie d’aujourd’hui.",
    "Que voyez-vous dans ces images ?": "Des objets anciens comme des lettres, reflétant la vie dans le passé.",
    "Selon vous, quel est le thème de la leçon ?": "La vie dans le passé et les différences avec la vie d'aujourd'hui.",
    "Micro-tâche 1 : Identifiez l’idée générale du texte": "Ce texte parle de la vie dans le passé et des différences avec la vie d’aujourd’hui.",
    "Micro-tâche 2 : (5 minutes) Déterminez les activités des gens dans le passé ?": "Dans le passé, les gens envoyaient des lettres, utilisaient les journaux, la radio et la télévision pour s’informer et ils passaient du temps à lire ou à pratiquer des activités en plein air.",
    "Micro-tâches 3 : (5 minutes) Trouvez les avantages de la vie sans Internet ?": "L’auteur essaie de montrer les avantages de la vie sans internet ni téléphone ; il affirme que les relations humaines étaient plus directes, que la vie favorisait une meilleure concentration et que les échanges réels se faisaient en face à face.",
    "Micro tâche 4 : (5 minutes) : Identifiez les inconvénients cités dans ce texte ?": "Les urgences étaient plus difficiles à gérer. Le contact avec des personnes éloignées restait compliqué. Certaines informations étaient difficiles à obtenir.",
    "Micro-tâches 5 : (5 minutes) : Comparez la vie dans le passé avec votre vie actuelle?": "Aujourd’hui, je peux envoyer un message immédiatement, contrairement au passé où il fallait attendre pour recevoir une lettre.",
    "Micro-tâches 6 : (5 minutes) : Conjuguez les verbes ?": "La communication se faisait par lettres. Les gens passaient plus de temps à discuter. Les informations circulaient lentement.",
    "Micro-tâches 7 : (5 minutes) : Donnez des exemples ?": "Les élèves devaient consulter plusieurs livres à la bibliothèque. Les recherches scolaires prenaient plus de temps.",
    "Micro-tâches 8 : (5 minutes) : Reformulez la phrase suivante ?": "Les nouvelles arrivaient moins vite et passaient par les journaux, la radio ou la télévision.",
    "Micro-tâches 9 : Mini-production : (10 minutes) Résumez le texte en trois phrases ?": "Ce texte décrit que la vie dans le passé était très différente d’aujourd’hui. De plus, les gens communiquaient par lettres ou en face à face. Sans Internet, les relations étaient plus directes et la concentration était meilleure."
  },
    "Leçon 2 : L’absence familiale et ses effets": {
    "Consigne\u00a0: Observez ce que vous voyez et prédisez le sujet ou le thème du texte.": "Ce texte parle de l’absence familiale et de la solitude qu’elle provoque.",
    "Consigne : Observez ce que vous voyez et prédisez le sujet ou le thème du texte.": "Ce texte parle de l’absence familiale et de la solitude qu’elle provoque.",
    "Que voyez-vous dans ces images ?": "Il y a dans l’image la vie familiale avant et après l’usage excessif de la technologie.",
    "Selon vous, quel est le thème de la leçon ?": "L'absence familiale et ses effets sur la vie quotidienne.",
    "Micro-tâche 1 : Identifiez l’idée générale du texte ?": "Ce texte parle de l’absence familiale et de la solitude qu’elle provoque",
    "Micro-tâche 2 : (5 minutes) : Après la lecture du texte, déduisez le sens des mots suivants selon le contexte :": "Éloignement : fait de vivre loin de sa famille. Solitude : sentiment d’être seul et sans soutien affectif. Isolement : situation d’une personne sans des relations sociales. Rompre l’isolement : casser – mettre fin à l’isolement.",
    "Micro-tâches 3 : (5 minutes) déterminez l’idée principale du texte puis relevez deux idées secondaires qui la développent.": "Idée principale : L’absence familiale a des effets négatifs sur la vie quotidienne et émotionnelle des enfants. Idées secondaires : L’éloignement cause la solitude.",
    "Micro tâche 4 : (5 minutes) : Listez trois conséquences de l’absence familiale ?": "La solitude prolongée, la tristesse, une perte de motivation et parfois un repli sur soi.",
    "Micro-tâches 5 : (5 minutes) : Pourquoi la solitude est-elle très difficile pour les personnes âgées selon le texte ? Justifiez votre réponse.": "La solitude est plus difficile pour les personnes âgées car elles vivent souvent seules et ont besoin de relations humaines directes.",
    "Micro-tâches 6 : (10 minutes) : Résumez le texte en 3 ou 4 phrases en utilisant vos propres vocabulaires ?": "L’éloignement familial provoque une solitude difficile à vivre, avec des conséquences sur l’équilibre émotionnel. Maintenir le contact et créer de nouveaux liens sociaux sont des solutions essentielles pour compenser cette absence."
  },
    "Leçon 3 : Le phénomène des influenceurs": {
    "Consigne\u00a0: Observez ce que vous voyez et prédisez le thème de la leçon.": "Ce texte parle de l’impact des influenceurs sur les opinions et les comportements des jeunes.",
    "Consigne : Observez ce que vous voyez et prédisez le thème de la leçon.": "Ce texte parle de l’impact des influenceurs sur les opinions et les comportements des jeunes.",
    "Que voyez-vous dans ces images ?": "Des personnes utilisant des smartphones, liées aux réseaux sociaux.",
    "Selon vous, quel est le thème de la leçon ?": "Le phénomène des influenceurs.",
    "Consigne : Selon les images ci-dessus, de quoi parle ce texte.": "Ce texte parle de l’impact des influenceurs sur les opinions et les comportements des jeunes.",
    "Micro-tâche 1 : Quel est le thème principal de ce texte ?": "Le rôle des influenceurs sur les réseaux sociaux et l’importance de les suivre de manière responsable.",
    "Micro-tâches 2 : (5 minutes) Trouvez le synonyme?": "Influence → impact / effet. Abonnés → personnes qui suivent. Promouvoir → encourager / faire connaître.",
    "Micro-tâches 3 : (5 minutes) : Relevez du texte une phrase qui montre le côté négatif des influenceurs.": "Certains sont critiqués pour encourager une consommation excessive.",
    "Micro-tâches 4 : (10 minutes) : Faire une comparaison?": "Dans ce texte, les influenceurs encouragent la consommation excessive de quelque produit. Dans la vie réelle, certains jeunes achètent des produits inutiles à cause des publicités en ligne.",
    "Micro-tâches 5 : (5 minutes) : Utilisez les mots suivants dans des phrases correctes : (influenceur – réseaux sociaux – publicité)": "L’influenceur partage une publicité sur les réseaux sociaux.",
    "Micro-tâches 6 : (5 minutes) : Reformulez la phrase suivante ?": "Ces influenceurs peuvent avoir un effet positif s’ils partagent des informations utiles et responsables.",
    "Micro-tâches 8 : Mini-production : (10 minutes) Résumez ce texte en trois phrases ?": "Les influenceurs sont présents sur les réseaux sociaux et partagent différents contenus. Leur influence peut être d’une part positive en transmettant des messages utiles ou d’autre part négative en encourageant une consommation excessive. Il est important de développer un esprit critique pour distinguer les informations fiables des publicités ou contenus inconvenables."
  }

};
